from .chat_controller import procesar_mensaje
from .clima_controller import obtener_clima
from .ayuda_controller import solicitar_ayuda
from .medicamento_controller import registrar_medicamento, obtener_medicamentos, obtener_medicamento_por_id, eliminar_medicamento_por_id, actualizar_medicamento
from .rutina_controller import registrar_rutina, obtener_rutinas, obtener_rutina_por_id, eliminar_rutina_por_id, actualizar_rutina, transformar_a_embed
from .asistente_controller import registrar_asistente, verificar_credenciales